### ISSUE TITLE
Class 'Kirby' not found in kirby-twig/config.php

### ISSUE THREAD

**Issue by MathiasGmeiner** [mgfagency/kirby-twig#1]
Hey, I tried to install this module on a clean Kirby 3 Beta 6 installation with PHP 7.1

## Steps
1. I installed it with composer, as written in the documentation.
2. Changed home.php to home.twig an modified the snippets to .twig
3. Reload of the page

## Error:
`Fatal error: Uncaught Error: Class 'Kirby' not found in /Users/.../Sites/.../vendor/mgfagency/kirby-twig/config.php on line 5`

Have I missed something? #

**Comment by seehat** [comment]
Hey @MathiasGmeiner, your steps were right. 

I think it only currently works with the composer based kirby install. (devkit) This is not intended.
Will fix this.

**Comment by MathiasGmeiner** [comment]
Thanks! In the meantime I try to change my installation to the devkit.

**Comment by theWeird** [comment]
Anything new on how to use this in a non-devkit setup?
I'm really interested in this plugin

**Comment by seehat** [comment]
The problem is this issue: https://github.com/k-next/kirby/issues/762

A workaround is using the devkit for now or with the starterkit manually downloading the repo to the plugin folder and installing composer dependencies inside the plugin. 

I will fix this, as soon as there is an official way to go for plugins.

**Comment by seehat** [comment]
This should be fixed in 1.0.7
